# Profile

spring:
  profiles:
    active: dev

---
# Datasource

spring:
  jpa:
    database: POSTGRESQL
    show_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    url: jdbc:postgresql://localhost:5432/magentadb
    username: postgres
    password: adminqwer

---
# Schema
spring:
  properties:
    javax:
      persistence:
        schema-generation:
          scripts:
            action: drop-and-create
            create-target: create.sql
            drop-target: drop.sql
            create-source: metadata
            drop-source: metadata
---
# Mail
spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    ssl: no
    tls: yes
    username: 2e2b32449f4ee8
    password: d15660ae3fb297
    protocol: smtp

  # Web

application:
  url: magenta/v1/

---
# Schedule

application:
  schedule:
    token-job: 0 0 0 * * ?

---
# Security

application:
  jwt:
    tokenPrefix: Bearer
    secret: Jjenta
    expiration-length: 15
  refresh:
    expiration-length: 2
  cors:
    allowed-origin: http://localhost:4200

---
# Mail

application:
  mail:
    address: magenta@mgn.com
    weekly-mail: 0 0 0 ? * SUN

---
# Images

application:
  image:
    size:
      cover-height: 100
      cover-width: 100
      profile-height: 50
      profile-width: 50
      logo-height: 30
      logo-width: 30
      thumbnail-height: 40
      thumbnail-width: 40

# Logging

logging:
  level:
    web: DEBUG